const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const promptIdx = args.indexOf('-p');
const prompt = promptIdx !== -1 ? args[promptIdx + 1] : 'Default Project';

console.log(`\n────────────────────────────────────────────────────────────`);
console.log(`[Claude Demo Mode] Initializing Autonomous Developer...`);
console.log(`────────────────────────────────────────────────────────────\n`);

async function delay(ms) {
  return new Promise(r => setTimeout(r, ms));
}

async function simulate() {
  const steps = [
    { msg: 'Analyzing project requirements...', d: 800 },
    { msg: 'Designing system architecture...', d: 1000 },
    { msg: 'Creating project structure and manifest...', d: 900 },
    { msg: 'Generating core application logic...', d: 1200 },
    { msg: 'Scaffolding automated test suites...', d: 800 },
    { msg: 'Formatting professional documentation...', d: 600 },
  ];

  for (const step of steps) {
    process.stdout.write(`i ${step.msg}\n`);
    await delay(step.d);
  }

  const p = prompt.toLowerCase();
  const outputDir = path.join(process.cwd(), 'demo-output');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  try {
    if (p.includes('chatbot') || p.includes('chat') || p.includes('react') || p.includes('ui') || p.includes('frontend')) {
      const projectDir = path.join(outputDir, 'react-chatbot');
      const srcDir = path.join(projectDir, 'src');
      const componentsDir = path.join(srcDir, 'components');
      [projectDir, srcDir, componentsDir].forEach(d => fs.mkdirSync(d, { recursive: true }));

      fs.writeFileSync(path.join(projectDir, 'package.json'), JSON.stringify({
        name: 'react-chatbot',
        version: '1.0.0',
        description: 'AI Chatbot App built by DevForge',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0' },
        devDependencies: { vite: '^5.0.0', '@vitejs/plugin-react': '^4.0.0' }
      }, null, 2));
      console.log('[Success] Created: package.json');

      fs.writeFileSync(path.join(projectDir, 'README.md'), `# React Chatbot App\n\nGenerated by DevForge AI Software Factory.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Features\n- Real-time chat UI\n- Message history\n- AI-powered responses\n`);
      console.log('[Success] Created: README.md');

      fs.writeFileSync(path.join(srcDir, 'index.jsx'), `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\ncreateRoot(document.getElementById('root')).render(<App />);\n`);
      console.log('[Success] Created: src/index.jsx');

      fs.writeFileSync(path.join(srcDir, 'App.jsx'), `import React, { useState } from 'react';\nimport ChatWindow from './components/ChatWindow';\nimport MessageInput from './components/MessageInput';\n\nconst App = () => {\n  const [messages, setMessages] = useState([\n    { id: 1, role: 'assistant', text: 'Hello! I am your AI assistant. How can I help you today?' }\n  ]);\n  const [isTyping, setIsTyping] = useState(false);\n\n  const handleSend = (text) => {\n    const userMsg = { id: Date.now(), role: 'user', text };\n    setMessages(prev => [...prev, userMsg]);\n    \n    setIsTyping(true);\n\n    const responses = [\n      "That is a great question! Let me check that for you.",\n      "I understand. Here is what I found regarding '" + text + "'.",\n      "I am processing your request. One moment please.",\n      "Interesting point. Could you tell me more?",\n      "I am trained to handle exactly that. Let me assist you!"\n    ];\n\n    setTimeout(() => {\n      const reply = responses[Math.floor(Math.random() * responses.length)];\n      const botMsg = { id: Date.now() + 1, role: 'assistant', text: reply };\n      setMessages(prev => [...prev, botMsg]);\n      setIsTyping(false);\n    }, 1500);\n  };\n\n  return (\n    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#0f172a' }}>\n      <div style={{ padding: '16px', background: '#1e293b', borderBottom: '1px solid #334155', display: 'flex', alignItems: 'center', gap: '8px' }}>\n        <div style={{ w: '8px', h: '8px', borderRadius: '50%', background: '#10b981' }}></div>\n        <h1 style={{ color: 'white', fontSize: '14px', fontWeight: '800', letterSpacing: '0.05em' }}>AI ASSISTANT</h1>\n      </div>\n      <ChatWindow messages={messages} isTyping={isTyping} />\n      <MessageInput onSend={handleSend} disabled={isTyping} />\n    </div>\n  );\n};\n\nexport default App;\n`);
      console.log('[Success] Created: src/App.jsx');

      fs.writeFileSync(path.join(componentsDir, 'ChatWindow.jsx'), `import React, { useRef, useEffect } from 'react';\n\nconst ChatWindow = ({ messages, isTyping }) => {\n  const endRef = useRef(null);\n  useEffect(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages, isTyping]);\n\n  return (\n    <div style={{ flex: 1, overflowY: 'auto', padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>\n      {messages.map(m => (\n        <div key={m.id} style={{ alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start',\n          background: m.role === 'user' ? '#6366f1' : '#1e293b',\n          color: '#f1f5f9', padding: '12px 18px', borderRadius: '16px', maxWidth: '70%',\n          boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}>\n          {m.text}\n        </div>\n      ))}\n      {isTyping && (\n        <div style={{ alignSelf: 'flex-start', background: '#1e293b', color: '#94a3b8', padding: '12px 18px', borderRadius: '16px', fontSize: '13px', fontStyle: 'italic' }}>\n          AI is thinking...\n        </div>\n      )}\n      <div ref={endRef} />\n    </div>\n  );\n};\n\nexport default ChatWindow;\n`);
      console.log('[Success] Created: src/components/ChatWindow.jsx');

      fs.writeFileSync(path.join(componentsDir, 'MessageInput.jsx'), `import React, { useState } from 'react';\n\nconst MessageInput = ({ onSend, disabled }) => {\n  const [text, setText] = useState('');\n  const handleSend = () => { if (text.trim() && !disabled) { onSend(text); setText(''); } };\n  const handleKey = (e) => { if (e.key === 'Enter') handleSend(); };\n\n  return (\n    <div style={{ display: 'flex', padding: '16px', gap: '12px', background: '#1e293b', borderTop: '1px solid #334155' }}>\n      <input value={text} onChange={e => setText(e.target.value)} onKeyDown={handleKey}\n        disabled={disabled}\n        placeholder={disabled ? "AI is thinking..." : "Type your message..."} \n        style={{ flex: 1, padding: '12px 16px', borderRadius: '12px', border: 'none',\n          background: '#0f172a', color: '#f1f5f9', fontSize: '14px', outline: 'none', opacity: disabled ? 0.5 : 1 }} />\n      <button onClick={handleSend} disabled={disabled}\n        style={{ padding: '12px 24px', borderRadius: '12px', background: disabled ? '#334155' : '#6366f1',\n          color: 'white', border: 'none', cursor: disabled ? 'default' : 'pointer', fontWeight: '600', transition: 'all 0.2s' }}>Send</button>\n    </div>\n  );\n};\n\nexport default MessageInput;\n`);
      console.log('[Success] Created: src/components/MessageInput.jsx');

      fs.writeFileSync(path.join(srcDir, 'index.css'), `* { margin: 0; padding: 0; box-sizing: border-box; }\nbody { font-family: 'Inter', sans-serif; background: #0f172a; }\n`);
      console.log('[Success] Created: src/index.css');

      fs.writeFileSync(path.join(projectDir, 'index.html'), `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>React Chatbot - DevForge</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/index.jsx"></script>\n</body>\n</html>\n`);
      console.log('[Success] Created: index.html');

      fs.writeFileSync(path.join(projectDir, 'vite.config.js'), `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 5174 }\n})\n`);
      console.log('[Success] Created: vite.config.js');

      console.log('\n[FINISH] DevForge Pipeline completed successfully! 9 files generated in demo-output/react-chatbot/');
      console.log('\n----------------------------------------');
      console.log('HOW TO RUN YOUR PROJECT:');
      console.log('  1. cd demo-output/react-chatbot');
      console.log('  2. npm install');
      console.log('  3. npm run dev');
      console.log('  Open: http://localhost:5174');
      console.log('----------------------------------------');

    } else if (p.includes('todo') || p.includes('api') || p.includes('node') || p.includes('express') || p.includes('rest')) {
      const projectDir = path.join(outputDir, 'node-api');
      const srcDir = path.join(projectDir, 'src');
      [projectDir, srcDir].forEach(d => fs.mkdirSync(d, { recursive: true }));

      fs.writeFileSync(path.join(projectDir, 'package.json'), JSON.stringify({
        name: 'node-api', version: '1.0.0',
        description: 'REST API built by DevForge',
        main: 'src/index.js',
        scripts: { start: 'node src/index.js', dev: 'nodemon src/index.js' },
        dependencies: { express: '^4.18.2', cors: '^2.8.5', dotenv: '^16.0.3' }
      }, null, 2));
      console.log('[Success] Created: package.json');

      fs.writeFileSync(path.join(srcDir, 'index.js'), `const express = require('express');\nconst cors = require('cors');\nrequire('dotenv').config();\n\nconst app = express();\napp.use(cors());\napp.use(express.json());\n\nconst todos = [];\n\napp.get('/todos', (req, res) => res.json(todos));\napp.post('/todos', (req, res) => {\n  const todo = { id: Date.now(), ...req.body };\n  todos.push(todo);\n  res.status(201).json(todo);\n});\napp.delete('/todos/:id', (req, res) => {\n  const idx = todos.findIndex(t => t.id == req.params.id);\n  if (idx === -1) return res.status(404).json({ error: 'Not found' });\n  todos.splice(idx, 1);\n  res.json({ success: true });\n});\n\nconst PORT = process.env.PORT || 3000;\napp.listen(PORT, () => console.log('Server running on port ' + PORT));\n`);
      console.log('[Success] Created: src/index.js');

      fs.writeFileSync(path.join(projectDir, 'README.md'), `# Node REST API\n\nGenerated by DevForge AI Software Factory.\n\n## Endpoints\n- GET /todos\n- POST /todos\n- DELETE /todos/:id\n`);
      console.log('[Success] Created: README.md');

      fs.writeFileSync(path.join(projectDir, '.env.example'), `PORT=3000\nNODE_ENV=development\n`);
      console.log('[Success] Created: .env.example');

      console.log('\n[FINISH] DevForge Pipeline completed successfully! 4 files generated in demo-output/node-api/');
      console.log('\n----------------------------------------');
      console.log('HOW TO RUN YOUR PROJECT:');
      console.log('  1. cd demo-output/node-api');
      console.log('  2. npm install');
      console.log('  3. node src/index.js');
      console.log('  API running at: http://localhost:3000');
      console.log('  Test endpoint: GET http://localhost:3000/todos');
      console.log('----------------------------------------');

    } else {
      // Generic project
      const projectDir = path.join(outputDir, 'devforge-project');
      fs.mkdirSync(projectDir, { recursive: true });
      fs.writeFileSync(path.join(projectDir, 'package.json'), JSON.stringify({ name: 'devforge-project', version: '1.0.0' }, null, 2));
      fs.writeFileSync(path.join(projectDir, 'README.md'), `# DevForge Project\n\nGenerated for: ${prompt}\n`);
      console.log('[Success] Created: package.json, README.md');
      console.log('\n[FINISH] DevForge Pipeline completed successfully!');
    }

    process.exit(0);
  } catch (e) {
    process.stderr.write('Error during generation: ' + e.message + '\n');
    process.exit(1);
  }
}

simulate();
